### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mkroening** [hermitcore/hermit-entry#2]
This project has several goals:

* [x] 1. Unify libhermit-rs' current boot info ABI under a new API.
    * [x] Published as `0.1`
    * [x] https://github.com/hermitcore/libhermit-rs/pull/462
    * [x] https://github.com/hermitcore/rusty-loader/pull/123
    * [x] https://github.com/hermitcore/uhyve/pull/335

* [x] 2. Analyze usage of the API
    * Make usage of the API sound
    * Reduce dependence on `RawBootInfo` where possible

* [x] 3. Rework the API

* [x] 4. https://github.com/hermitcore/hermit-entry/issues/1

* [x] 5. Create a new ABI version
